mypjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

mypjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('',views.index, name='index'),
    path('create/',views.create, name='create'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/update/',views.update, name='update'),
    path('<int:pk>/delete/',views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete',views.comments_delete,name='comments_delete'),
    path('<int:movie_pk>/likes/',views.likes, name='likes'),
]

mypjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

mypjt/movies/models.py
from statistics import mode
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings
# Create your models here.
class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movie')
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, null=True)
    content=models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

mypjt/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    title = forms.CharField(
        widget = forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'Title',
        })
    )

    audience = forms.IntegerField(
        widget= forms.NumberInput(attrs={
            'class':'form-control',
            'placeholder':'Audience',
        })
    )

    release_date = forms.DateField(
        widget = forms.DateInput(attrs={
            'class':'form-control',
            'placeholder':'연도-월-일',
            'type':'date',
        })
    )

    GENRE_COICES = (
        ('코미디','코미디'),
        ('공포','공포'),
        ('로맨스','로맨스'),
        ('19금','19금'),
        ('액션','액션'),
        ('애니매이션','애니매이션'),
        ('다큐멘터리','다큐멘터리'),
        ('드라마','드라마'),
    )
    genre = forms.ChoiceField(
        widget = forms.Select(attrs={
            'class':'form-control',
        }),
        choices = GENRE_COICES
    )

    score = forms.FloatField(
        widget = forms.NumberInput(attrs={
            'min':'0',
            'max':'10',
            'step':'0.1',
            'class':'form-control',
            'placeholder':'Score',
        })
    )

    poster_url = forms.CharField(
        widget = forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'Poster url',
        })
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={
            'class':'form-control',
            'placeholder':'Description',
        })
    )

    class Meta:
        model = Movie
        exclude = ('user',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('movie','user',)

mypjt/movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required
from .models import Movie, Comment
from .forms import MovieForm, CommentForm

# Create your views here.
@require_safe
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies,
    }
    return render(request, 'movies/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail',movie.pk)
    else:
        form = MovieForm()
    context = {
        'form':form,
    }
    return render(request, 'movies/create.html', context)

@require_safe
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie':movie,
        'comment_form':comment_form,
        'comments':comments,
    }
    return render(request, 'movies/detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user == movie.user:
        if request.method == 'POST':
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                form.save()
                return redirect('movies:detail',movie.pk)
        else:
            form = MovieForm(instance=movie)
    else:
        return redirect('movies:index')
    context = {
        'form':form,
        'movie':movie,
    }
    return render(request, 'movies/update.html', context)

@login_required
def delete(request,pk):
    movie = Movie.objects.get(pk=pk)
    if request.user.is_authenticated:
        if request.user == movie.user:
            movie.delete()
            return redirect('movies:index')
    return redirect('movies:detail', movie.pk)

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect('movies:detail', movie.pk)
    return redirect('movies:login')

@require_POST
def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('movies:detail', movie_pk)

@require_POST
def likes(request, movie_pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=movie_pk)
        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:index')
    return redirect('movies:login')

mypjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<div class="m-5">
  <h1 class="d-flex justify-content-center">CREATE</h1>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-secondary text-white">
  </form>
  <hr>
  <button type="button" class="btn btn-outline-secondary"><a href="{% url 'movies:index' %}" class="text-decoration-none text-white fs-5">BACK</a></a></button>
</div>
{% endblock content %}

mypjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="d-flex justify-content-center">DETAIL</h1>
    <hr>
    <div class="d-flex justify-content-center">
        <div class="card mb-3 col-9 ">
            <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ movie.poster_url }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body text-dark">
                <h3 class="card-title">{{ movie.title }}</h3>
                <p class="card-text">Release Dates : {{ movie.release_date }}</p>
                <p class="card-text">Genre : {{ movie.genre }}</p>
                <p class="card-text">Score : {{ movie.score }}</p> 
                <p class="card-text">{{ movie.description }}</p>
                <br>
                <div>
                    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'movies:update' movie.pk %}" class="text-decoration-none text-dark fs-5">UPDATE</a></button>
                    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'movies:delete' movie.pk %}" class="text-decoration-none text-dark fs-5">DELETE</a></button>
                </div>
                <br>
                <a href="{% url 'movies:index' %}" class="text-decoration-none text-dark fs-5">BACK</a>
                </div>
            </div>
            </div>
        </div>
    </div>
    <h4>댓글 목록</h4>
    {% if comments %}
        <p>{{ comments|length }}개의 댓글이 있습니다.</p>
    {% endif %}
    <ul style="list-style-type: square;">
        {% for comment in comments %}
            <li class="d-flex">
                {{comment.user}} : {{comment.content}}&nbsp&nbsp

                {% if request.user == comment.user %}
                    <form action="{% url 'movies:comments_delete' movie.pk comment.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="DEL" class="btn btn-outline-secondary sm" style="--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .2rem; --bs-btn-font-size: .5rem;">
                    </form>
                {% endif %}
            </li>
        {% empty %}
            <li>댓글이 없습니다.</li>
        {% endfor %}
    </ul>
    <hr>
    {% if request.user.is_authenticated %}
        <form action="{% url 'movies:comments_create' movie.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <input type="submit" value="댓글입력">
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
    {% endif %}
{% endblock content %}

mypjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="d-flex justify-content-center">Movies</h1>
    <hr>
    <div class="d-flex justify-content-center">
        <div class="container row ">
            {% for movie in movies %}
                <div class="card col-4">
                    <img src="{{ movie.poster_url }}" class="card-img-top mt-2" width="100%" alt="#">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'movies:detail' movie.pk %}" class="text-decoration-none text-dark fs-5">{{ movie.title }}</a></h5>
                        <p class="card-text text-dark"> 💕 {{ movie.score }} </p>
                        <p class="card-text text-dark">follow:{{movie.like_users.all|length}}</p>
                        <form action="{% url 'movies:likes' movie.pk %}" method="POST">
                            {% csrf_token %}
                            {% if request.user in movie.like_users.all %}
                                <input type="submit" value="cancel">
                            {% else %}
                                <input type="submit" value="like">
                            {% endif %}
                        </form>
                    </div>
                </div>
            {% endfor %}
            <hr>
        </div>
    </div>
{% endblock content %}

mypjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>UPDATE</h1>
    <form action="{% url 'movies:update' movie.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
        <input type="submit" name="cancel" value="Cancel">
    </form>
    <hr>
    <a href="{% url 'movies:index' %}" class="text-decoration-none text-dark fs-5">BACK</a>
{% endblock content %}