mypjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

mypjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('',views.index, name='index'),
    path('create/',views.create, name='create'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/update/',views.update, name='update'),
    path('<int:pk>/delete/',views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete',views.comments_delete,name='comments_delete'),
    path('<int:movie_pk>/likes/',views.likes, name='likes'),
]

mypjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

mypjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Eom Movie</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap');

    body {
        font-family: 'Nanum Myeongjo', serif;
        background-color: black;
    }
  </style>
</head>
<body class="bg-dark text-white">
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <img src="https://images.descentekorea.co.kr/contents/event/about_UMB/2021_renew/ec/about_umbro_renew_topTxt.png" alt="#" width="50px">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active text-white" href="{% url 'accounts:profile' user.username %}">{{ user }}님, 환영합니다.</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href="{% url 'movies:index' %}">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'movies:create' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:update' %}">회원정보 변경</a>
          </li>
          <li class="nav-item">
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="회원탈퇴" class="nav-link text-white bg-dark border border-dark">
            </form>
          </li>
          <li class="nav-item">
            <form action="{% url 'accounts:delete' %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="Logout" class="nav-link text-white bg-dark border border-dark">
            </form>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'accounts:signup' %}">Signup</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link text-white" href="https://www.justwatch.com/kr/%EC%98%81%ED%99%94">Watch</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>